name: Build Pyarrow wheel for ARM

on:
  push:
    branches:
      - main
      - ci/*
  pull_request:
  workflow_dispatch:
    inputs:
      arrow_version:
        type: string
        description: Arrow version to build
        required: true
        default: "21.0.0"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Building for ${{ inputs.arrow_version || '21.0.0' }} on ${{ matrix.python-version }}
    env:
      ARROW_VERSION: "${{ inputs.arrow_version || '21.0.0' }}"

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Build Pyarrow wheels
      run: |
        docker buildx build -f Dockerfile \
          --platform linux/arm/v7 \
          --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
          --build-arg ARROW_VERSION=${{ env.ARROW_VERSION }} \
          --load \
          -t pyarrow:wheel .

    - name: Extract Wheels from image
      run: |
        docker run --rm -v $(pwd)/assets:/assets \
          --platform linux/arm/v7 \
          pyarrow:wheel \
          cp -r /build/arrow/python/dist /assets/

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pyarrow-wheels-${{ matrix.python-version }}
        path: ./assets/dist/


  combine:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: pyarrow_wheels
        pattern: pyarrow-wheels-*
        merge-multiple: true

    - name: Upload combined artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pyarrow-wheels-combined
        path: pyarrow_wheels/
